# Generated by Django 3.0.3 on 2020-05-21 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this prescription', primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Enter patient name ', max_length=200)),
                ('symptoms', models.CharField(help_text='Enter  symptoms ', max_length=200)),
                ('diagnosis', models.CharField(help_text='Enter  diagnosis ', max_length=200)),
                ('pescription', models.CharField(help_text='Enter  pescription ', max_length=200)),
                ('advice', models.CharField(help_text='Enter  advice ', max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
