# Generated by Django 3.0.3 on 2020-05-22 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200522_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='advice',
            field=models.TextField(help_text='Enter  advice ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='diagnosis',
            field=models.TextField(help_text='Enter  diagnosis ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pescription',
            field=models.TextField(help_text='Enter  pescription ', max_length=1000),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='symptoms',
            field=models.TextField(help_text='Enter  symptoms ', max_length=1000),
        ),
    ]
